name: build
on:
  push:
    branches: [ main ]
    paths-ignore: [ README.md, justfile]
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Install Build Dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install fuse-overlayfs podman

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build image
        run: |
          just build

      - name: Deploy image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io --username=${GITHUB_REPOSITORY_OWNER} --password-stdin
          just push ghcr.io/${GITHUB_REPOSITORY_OWNER}
